/**
 * Image Generation Service
 *
 * Uses Google's Nano Banana (Gemini 2.5 Flash Image) model via fal.ai
 * for generating t-shirt designs from text prompts.
 *
 * Model: fal-ai/nano-banana
 * API: https://fal.ai/models/fal-ai/nano-banana/api
 */

import { fal } from "@fal-ai/client";

// Configure fal.ai client with API key
if (process.env.FAL_KEY) {
  fal.config({
    credentials: process.env.FAL_KEY as string,
  });
}

/**
 * Generates an image from a text prompt using Nano Banana model
 *
 * @param prompt - Text description of the desired t-shirt design
 * @returns Base64-encoded data URL of the generated image
 * @throws Error if generation fails or API key is not configured
 */
export const generateImage = async (prompt: string): Promise<string> => {
  try {
    if (!process.env.FAL_KEY) {
      throw new Error("FAL_KEY environment variable is not set. Please add it to your .env.local file.");
    }

    console.log('Generating image with Nano Banana model via fal.ai...');
    console.log('Prompt:', prompt);

    // Run the Nano Banana model via fal.ai
    const result = await fal.subscribe("fal-ai/nano-banana", {
      input: {
        prompt: `A professional, high-resolution t-shirt design graphic featuring: ${prompt}. Centered, on a transparent or solid background, vector style, suitable for printing on t-shirts.`,
        num_images: 1,
        output_format: "png",
        aspect_ratio: "1:1",
        sync_mode: false, // We'll fetch the URL and convert to base64
      },
      logs: true,
      onQueueUpdate: (update) => {
        if (update.status === "IN_PROGRESS") {
          update.logs?.map((log) => log.message).forEach(console.log);
        }
      },
    });

    console.log('Nano Banana result:', result);

    // Extract the image URL from the result
    if (result.data && result.data.images && result.data.images.length > 0) {
      const imageUrl = result.data.images[0].url;
      console.log('Image URL:', imageUrl);

      // Fetch the image and convert to base64
      const imageResponse = await fetch(imageUrl);

      if (!imageResponse.ok) {
        throw new Error(`Failed to fetch generated image: ${imageResponse.statusText}`);
      }

      // Convert to blob then to base64
      const blob = await imageResponse.blob();
      const arrayBuffer = await blob.arrayBuffer();
      const base64 = Buffer.from(arrayBuffer).toString('base64');

      // Return as data URL
      return `data:image/png;base64,${base64}`;
    } else {
      throw new Error("No image was generated by Nano Banana model");
    }
  } catch (error) {
    console.error("Error generating image with Nano Banana:", error);

    if (error instanceof Error) {
      throw new Error(`Failed to generate image: ${error.message}`);
    } else {
      throw new Error("Failed to generate image. Please check your prompt and FAL_KEY.");
    }
  }
};

/**
 * Check if fal.ai API key is configured
 */
export const isConfigured = (): boolean => {
  return !!process.env.FAL_KEY;
};
