/**
 * Image Generation Service
 *
 * Uses Google's Nano Banana (Gemini 2.5 Flash Image) model via fal.ai
 * for generating t-shirt designs from text prompts.
 *
 * Security: API calls are made through a Supabase Edge Function to keep
 * the FAL_KEY secure on the server side.
 *
 * Model: fal-ai/nano-banana
 * API: https://fal.ai/models/fal-ai/nano-banana/api
 */

import { supabase } from './supabaseClient';

/**
 * Generates an image from a text prompt using Nano Banana model
 * via Supabase Edge Function (keeps API key secure server-side)
 *
 * @param prompt - Text description of the desired t-shirt design
 * @returns Base64-encoded data URL of the generated image
 * @throws Error if generation fails
 */
export const generateImage = async (prompt: string): Promise<string> => {
  try {
    console.log('Generating image with Nano Banana model via Supabase Edge Function...');
    console.log('Prompt:', prompt);

    // Call Supabase Edge Function for secure image generation
    const { data, error } = await supabase.functions.invoke('generate-image', {
      body: {
        prompt: `A professional, high-resolution t-shirt design graphic featuring: ${prompt}. Centered, on a transparent or solid background, vector style, suitable for printing on t-shirts.`,
      },
    });

    if (error) {
      throw new Error(`Edge Function error: ${error.message}`);
    }

    if (!data || !data.imageDataUrl) {
      throw new Error("No image was generated by Nano Banana model");
    }

    // Return the base64 data URL from the Edge Function
    return data.imageDataUrl;
  } catch (error) {
    console.error("Error generating image:", error);

    if (error instanceof Error) {
      throw new Error(`Failed to generate image: ${error.message}`);
    } else {
      throw new Error("Failed to generate image. Please check your prompt and try again.");
    }
  }
};

/**
 * Check if image generation is available
 * (Always returns true since Edge Function handles configuration)
 */
export const isConfigured = (): boolean => {
  return true;
};
