// Supabase Edge Function for secure image generation
// This keeps the FAL_KEY secure on the server side

import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { fal } from "npm:@fal-ai/client@latest";

Deno.serve(async (req: Request) => {
  try {
    // Only allow POST requests
    if (req.method !== "POST") {
      return new Response(
        JSON.stringify({ error: "Method not allowed" }),
        { status: 405, headers: { "Content-Type": "application/json" } }
      );
    }

    // Get FAL_KEY from environment (set in Supabase dashboard)
    const falKey = Deno.env.get("FAL_KEY");
    if (!falKey) {
      return new Response(
        JSON.stringify({ error: "FAL_KEY not configured in Supabase Edge Function environment" }),
        { status: 500, headers: { "Content-Type": "application/json" } }
      );
    }

    // Configure fal.ai client
    fal.config({
      credentials: falKey,
    });

    // Parse request body
    const { prompt } = await req.json();

    if (!prompt || typeof prompt !== "string") {
      return new Response(
        JSON.stringify({ error: "Prompt is required" }),
        { status: 400, headers: { "Content-Type": "application/json" } }
      );
    }

    console.log("Generating image with prompt:", prompt);

    // Run the Nano Banana model via fal.ai
    const result = await fal.subscribe("fal-ai/nano-banana", {
      input: {
        prompt: prompt,
        num_images: 1,
        output_format: "png",
        aspect_ratio: "1:1",
        sync_mode: false,
      },
      logs: true,
      onQueueUpdate: (update) => {
        if (update.status === "IN_PROGRESS") {
          update.logs?.map((log) => log.message).forEach(console.log);
        }
      },
    });

    console.log("Nano Banana result received");

    // Extract the image URL from the result
    if (result.data && result.data.images && result.data.images.length > 0) {
      const imageUrl = result.data.images[0].url;
      console.log("Image URL:", imageUrl);

      // Fetch the image and convert to base64
      const imageResponse = await fetch(imageUrl);

      if (!imageResponse.ok) {
        throw new Error(`Failed to fetch generated image: ${imageResponse.statusText}`);
      }

      // Convert to blob then to base64
      const blob = await imageResponse.blob();
      const arrayBuffer = await blob.arrayBuffer();
      const base64 = Buffer.from(arrayBuffer).toString("base64");

      // Return as data URL
      const imageDataUrl = `data:image/png;base64,${base64}`;

      return new Response(
        JSON.stringify({ imageDataUrl }),
        { status: 200, headers: { "Content-Type": "application/json" } }
      );
    } else {
      return new Response(
        JSON.stringify({ error: "No image was generated by Nano Banana model" }),
        { status: 500, headers: { "Content-Type": "application/json" } }
      );
    }
  } catch (error) {
    console.error("Error in generate-image Edge Function:", error);
    return new Response(
      JSON.stringify({
        error: error instanceof Error ? error.message : "Unknown error occurred",
      }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }
});




